In [ ]:
Complete the function solveMeFirst to compute the sum of two integers.
Function prototype:
int solveMeFirst(int a, int b);
where,
a is the first integer input.
b is the second integer input
Return values
sum of the above two integers

def solveMeFirst(a,b):
	# Hint: Type return a+b below
    return a+b


num1 = int(input())
num2 = int(input())
res = solveMeFirst(num1,num2)
print(res)

In [51]:
# What is Dense Ranking?

# In dense ranking, items that compare equally receive the same ranking number
# and the next item(s) receive the immediately following ranking number. 

# Thus if A ranks ahead of B and C (which compare equal) which are both ranked ahead of D, 
# then A gets ranking number 1 ("first"),
# B gets ranking number 2 ("joint second"),
# C also gets ranking number 2 ("joint second") and D gets ranking number 3 ("Third")

# Alice is playing an arcade game and wants to climb to the top of the leaderboard and wants to track her ranking.
# The game uses Dense Ranking, so its leaderboard works like this:
# The player with the highest score is ranked number 1 on the leaderboard.
# Players who have equal scores receive the same ranking number,
# and the next player(s) receive the immediately following ranking number.

# Function Description
# Complete the climbingLeaderboard function in the editor below. It should return an integer array where each element res[j]
#represents Alice's rank after the jth game.
# climbingLeaderboard has the following parameter(s):
# scores: an array of integers that represent leaderboard scores
# alice: an array of integers that represent Alice's scores
    
# Input Format
# The first line contains an integer n, the number of players on the leaderboard. 
# The next line contains n space-separated integers scores[i], the leaderboard scores in decreasing order. 
# The next line contains an integer, m, denoting the number games Alice plays. 
# The last line contains m space-separated integers alice[j], the game scores.


!/bin/python3

import math
import os
import random
import re
import sys

# Complete the climbingLeaderboard function below.
def climbingLeaderboard(scores, alice):
    s = sorted(set(scores), reverse=True)
    p = len(s)
    ranks = []
    
    for c in alice:
        while p >= 1 and c >= s[p - 1]:
            p -= 1
        ranks.append(p + 1)    
    
    return ranks
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    scores_count = int(input())

    scores = list(map(int, input().rstrip().split()))

    alice_count = int(input())

    alice = list(map(int, input().rstrip().split()))

    result = climbingLeaderboard(scores, alice)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()


In [31]:
from scipy.stats import rankdata
rankdata([1,1,6,90], method='min')

array([1, 1, 3, 4])

In [33]:
import numpy
array = numpy.array([4,2,7,1])
temp = array.argsort()

In [34]:
temp

array([3, 1, 0, 2])

In [35]:
array

array([4, 2, 7, 1])

In [36]:
ranks = numpy.empty_like(temp)
ranks[temp] = numpy.arange(len(array))

In [37]:
ranks

array([2, 1, 3, 0])

In [45]:
import numpy
array = numpy.array([4,2,2,1])
temp = array.argsort()
ranks = numpy.empty_like(temp)
#ranks
ranks[temp] = numpy.arange(len(array))
# ranks

array([0, 1, 2, 3])

In [40]:
import numpy
array = numpy.array([4,2,2,1])
temp = array.argsort(kind='quicksort')
temp

array([3, 1, 2, 0])

In [41]:
import numpy
array = numpy.array([4,2,2,1])
temp = array.argsort(kind='mergesort')
temp

array([3, 1, 2, 0])

In [42]:
import numpy
array = numpy.array([4,2,2,1])
temp = array.argsort(kind='heapsort')
temp

array([3, 2, 1, 0])

In [ ]:
numpy.empty_like:
Return a new array with the same shape and type as a given array.

array.argsort
Returns the indices that would sort an array.

numpy.arange
Return evenly spaced values within a given interval.
example:
>>> np.arange(3)
array([0, 1, 2])

In [76]:
#looks like broken - not working for single element or even double elements
def leaderboard_climb(arr, kara):
    scores = sorted(set(arr), reverse=True)
    position = len(scores)
    ranks = []
    
    for checkpoint in kara:
        while position >= 1 and checkpoint >= scores[position - 1]:
            position -= 1
        ranks.append(position + 1)    
    
    return ranks

In [77]:
leaderboard_climb([120, 67, 45, 12], [5, 90, 1000])

[5, 2, 1]